global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tor-proxy-pool'

scrape_configs:
  - job_name: 'tor-proxy-pool'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
